spring:
    profiles:
        active: dev
    servlet:
        multipart:
            max-file-size: 50MB
    jackson:
        time-zone: Europe/Paris
springdoc:
    default-produces-media-type: application/json
server:
    servlet:
        context-path: /api/v1/

